"""add webhooks

Revision ID: c8e2d4a10b93
Revises: f3a9c2b71e40
Created: 2026-07-25 12:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Custom column types referenced by autogenerated definitions.
import app.db.types  # noqa: F401

revision: str = 'c8e2d4a10b93'
down_revision: str | None = 'f3a9c2b71e40'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'webhook_endpoints',
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('url', sa.String(length=2048), nullable=False),
        sa.Column('description', sa.String(length=100), nullable=True),
        sa.Column('secret', sa.String(length=80), nullable=False),
        sa.Column('events', sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column('last_delivery_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'],
            name=op.f('fk_webhook_endpoints_user_id_users'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_endpoints')),
    )
    op.create_index(
        op.f('ix_webhook_endpoints_user_id'), 'webhook_endpoints', ['user_id'], unique=False
    )

    op.create_table(
        'webhook_deliveries',
        sa.Column('endpoint_id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(length=64), nullable=False),
        sa.Column('event_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            'status',
            sa.Enum(
                'pending', 'succeeded', 'failed', 'exhausted', 'suppressed',
                name='webhook_delivery_status',
            ),
            server_default='pending',
            nullable=False,
        ),
        sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
        sa.Column('max_attempts', sa.Integer(), nullable=False),
        sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('last_status_code', sa.Integer(), nullable=True),
        sa.Column('last_error', sa.String(length=300), nullable=True),
        sa.Column('last_duration_ms', sa.BigInteger(), nullable=True),
        sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['endpoint_id'], ['webhook_endpoints.id'],
            name=op.f('fk_webhook_deliveries_endpoint_id_webhook_endpoints'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_deliveries')),
    )
    op.create_index(
        op.f('ix_webhook_deliveries_endpoint_id'),
        'webhook_deliveries', ['endpoint_id'], unique=False,
    )
    op.create_index(
        'ix_webhook_deliveries_due',
        'webhook_deliveries', ['next_attempt_at'], unique=False,
        postgresql_where=sa.text("status in ('pending', 'failed')"),
    )


def downgrade() -> None:
    op.drop_index('ix_webhook_deliveries_due', table_name='webhook_deliveries')
    op.drop_index(op.f('ix_webhook_deliveries_endpoint_id'), table_name='webhook_deliveries')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_webhook_endpoints_user_id'), table_name='webhook_endpoints')
    op.drop_table('webhook_endpoints')
    op.execute("DROP TYPE IF EXISTS webhook_delivery_status")
