"""initial schema

Revision ID: ad9dc7da6bf2
Revises: 
Created: 2026-07-23 05:26:00.637121
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Custom column types referenced by autogenerated definitions.
import app.db.types  # noqa: F401
from app.db.search import (
    CREATE_SEARCH_VECTOR_FUNCTION,
    CREATE_SEARCH_VECTOR_TRIGGER,
    DROP_SEARCH_VECTOR_FUNCTION,
    DROP_SEARCH_VECTOR_TRIGGER,
)

revision: str = 'ad9dc7da6bf2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# PostgreSQL native enum types created implicitly by the table definitions above.
# Alembic does not drop these automatically, so downgrade() removes them by name;
# without this a downgrade followed by an upgrade fails with "type already exists".
ENUM_TYPES = (
    "account_status",
    "agent_status",
    "agent_verification_tier",
    "dispute_resolution",
    "escrow_status",
    "notification_category",
    "notification_channel",
    "notification_delivery_status",
    "order_status",
    "pricing_model",
    "review_status",
    "service_status",
    "transaction_status",
    "transaction_type",
    "user_role",
    "wallet_provider",
    "wallet_verification_status",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('slug', app.db.types.LowercaseString(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9][a-z0-9-]{1,63}$'", name=op.f('ck_categories_slug_format')),
    sa.CheckConstraint('parent_id IS NULL OR parent_id <> id', name=op.f('ck_categories_no_self_parent')),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], name=op.f('fk_categories_parent_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_index('ix_categories_parent_id_sort_order', 'categories', ['parent_id', 'sort_order'], unique=False)
    op.create_table('siwe_nonces',
    sa.Column('nonce', sa.String(length=96), nullable=False),
    sa.Column('address', app.db.types.EthereumAddress(length=42), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_siwe_nonces')),
    sa.UniqueConstraint('nonce', name=op.f('uq_siwe_nonces_nonce'))
    )
    op.create_index('ix_siwe_nonces_expires_at', 'siwe_nonces', ['expires_at'], unique=False)
    op.create_table('users',
    sa.Column('primary_address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('username', app.db.types.LowercaseString(length=32), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.String(length=600), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('email', app.db.types.LowercaseString(length=320), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), server_default='user', nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended_by_user', 'suspended_by_admin', 'deactivated', name='account_status'), server_default='active', nullable=False),
    sa.Column('preferred_locale', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('terms_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email IS NULL OR position('@' in email) > 1", name=op.f('ck_users_email_shape')),
    sa.CheckConstraint("username IS NULL OR username ~ '^[a-z0-9][a-z0-9_-]{2,31}$'", name=op.f('ck_users_username_format')),
    sa.CheckConstraint('email_verified_at IS NULL OR email IS NOT NULL', name=op.f('ck_users_email_verified_requires_email')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('primary_address', name=op.f('uq_users_primary_address')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_index('ix_users_status_created_at', 'users', ['status', 'created_at'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('order', 'payment', 'message', 'reputation', 'security', 'system', name='notification_category'), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', name='notification_channel'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_preferences')),
    sa.UniqueConstraint('user_id', 'category', 'channel', name='user_category_channel')
    )
    op.create_index('ix_notification_preferences_user_id', 'notification_preferences', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_sessions_refresh_token_hash'))
    )
    op.create_index('ix_sessions_expires_at', 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_user_id_expires_at', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_table('wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('chain_id', sa.Integer(), server_default='8453', nullable=False),
    sa.Column('label', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.Enum('metamask', 'coinbase', 'walletconnect', 'injected', 'other', name='wallet_provider'), server_default='other', nullable=False),
    sa.Column('verification_status', sa.Enum('unverified', 'verified', 'revoked', name='wallet_verification_status'), server_default='unverified', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_message', sa.String(length=2048), nullable=True),
    sa.Column('is_payout', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(verification_status = 'verified') = (verified_at IS NOT NULL)", name=op.f('ck_wallets_verified_at_matches_status')),
    sa.CheckConstraint("NOT is_payout OR verification_status = 'verified'", name=op.f('ck_wallets_payout_requires_verification')),
    sa.CheckConstraint('chain_id > 0', name=op.f('ck_wallets_chain_id_positive')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_wallets_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    sa.UniqueConstraint('address', 'chain_id', name='address_chain')
    )
    op.create_index('ix_wallets_user_id', 'wallets', ['user_id'], unique=False)
    op.create_index('uq_wallets_one_payout_per_user', 'wallets', ['user_id'], unique=True, postgresql_where=sa.text('is_payout'))
    op.create_table('agents',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('slug', app.db.types.LowercaseString(length=64), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('tagline', sa.String(length=160), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'suspended', 'retired', name='agent_status'), server_default='draft', nullable=False),
    sa.Column('verification_tier', sa.Enum('unverified', 'domain_verified', 'organization_verified', name='agent_verification_tier'), server_default='unverified', nullable=False),
    sa.Column('payout_wallet_id', sa.UUID(), nullable=True),
    sa.Column('payout_address', app.db.types.EthereumAddress(length=42), nullable=True),
    sa.Column('website_url', sa.String(length=512), nullable=True),
    sa.Column('verified_domain', app.db.types.LowercaseString(length=253), nullable=True),
    sa.Column('domain_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('api_endpoint', sa.String(length=512), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancelled_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disputed_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_sum', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9][a-z0-9-]{1,63}$'", name=op.f('ck_agents_slug_format')),
    sa.CheckConstraint("status <> 'active' OR payout_wallet_id IS NOT NULL", name=op.f('ck_agents_active_agent_requires_payout_wallet')),
    sa.CheckConstraint("verification_tier = 'unverified' OR verified_domain IS NOT NULL", name=op.f('ck_agents_verified_tier_requires_domain_proof')),
    sa.CheckConstraint('(payout_wallet_id IS NULL) = (payout_address IS NULL)', name=op.f('ck_agents_payout_address_matches_wallet')),
    sa.CheckConstraint('(verified_domain IS NULL) = (domain_verified_at IS NULL)', name=op.f('ck_agents_domain_verification_consistent')),
    sa.CheckConstraint('cancelled_orders >= 0', name=op.f('ck_agents_cancelled_orders_non_negative')),
    sa.CheckConstraint('completed_orders >= 0', name=op.f('ck_agents_completed_orders_non_negative')),
    sa.CheckConstraint('disputed_orders >= 0', name=op.f('ck_agents_disputed_orders_non_negative')),
    sa.CheckConstraint('rating_sum >= 0 AND rating_sum <= review_count * 5', name=op.f('ck_agents_rating_sum_within_bounds')),
    sa.CheckConstraint('review_count >= 0', name=op.f('ck_agents_review_count_non_negative')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_agents_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payout_wallet_id'], ['wallets.id'], name=op.f('fk_agents_payout_wallet_id_wallets'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agents')),
    sa.UniqueConstraint('slug', name=op.f('uq_agents_slug'))
    )
    op.create_index('ix_agents_capabilities', 'agents', ['capabilities'], unique=False, postgresql_using='gin')
    op.create_index('ix_agents_owner_id', 'agents', ['owner_id'], unique=False)
    op.create_index('ix_agents_status_published_at', 'agents', ['status', 'published_at'], unique=False)
    op.create_table('agent_domain_challenges',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('domain', app.db.types.LowercaseString(length=253), nullable=False),
    sa.Column('token', sa.String(length=96), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('dns_txt', 'well_known')", name=op.f('ck_agent_domain_challenges_method_supported')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_agent_domain_challenges_attempt_count_non_negative')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_agent_domain_challenges_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_domain_challenges')),
    sa.UniqueConstraint('agent_id', 'domain', name='agent_domain'),
    sa.UniqueConstraint('token', name=op.f('uq_agent_domain_challenges_token'))
    )
    op.create_index('ix_agent_domain_challenges_agent_id', 'agent_domain_challenges', ['agent_id'], unique=False)
    op.create_table('reputation_snapshots',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('completed_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('cancelled_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disputed_orders', sa.Integer(), server_default='0', nullable=False),
    sa.Column('disputes_lost', sa.Integer(), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_sum', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=38, scale=6), server_default='0', nullable=False),
    sa.Column('volume_currency', sa.String(length=12), server_default='USDC', nullable=False),
    sa.Column('median_delivery_hours', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('on_time_delivery_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('algorithm_version', sa.String(length=16), server_default='v1', nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('cancelled_orders >= 0', name=op.f('ck_reputation_snapshots_cancelled_non_negative')),
    sa.CheckConstraint('completed_orders >= 0', name=op.f('ck_reputation_snapshots_completed_non_negative')),
    sa.CheckConstraint('disputed_orders >= 0', name=op.f('ck_reputation_snapshots_disputed_non_negative')),
    sa.CheckConstraint('disputes_lost >= 0 AND disputes_lost <= disputed_orders', name=op.f('ck_reputation_snapshots_disputes_lost_within_disputed')),
    sa.CheckConstraint('median_delivery_hours IS NULL OR median_delivery_hours >= 0', name=op.f('ck_reputation_snapshots_median_delivery_non_negative')),
    sa.CheckConstraint('on_time_delivery_rate IS NULL OR (on_time_delivery_rate >= 0 AND on_time_delivery_rate <= 1)', name=op.f('ck_reputation_snapshots_on_time_rate_in_range')),
    sa.CheckConstraint('rating_sum >= 0 AND rating_sum <= review_count * 5', name=op.f('ck_reputation_snapshots_rating_sum_within_bounds')),
    sa.CheckConstraint('review_count >= 0', name=op.f('ck_reputation_snapshots_review_count_non_negative')),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name=op.f('ck_reputation_snapshots_score_in_range')),
    sa.CheckConstraint('total_volume >= 0', name=op.f('ck_reputation_snapshots_volume_non_negative')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_reputation_snapshots_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reputation_snapshots')),
    sa.UniqueConstraint('agent_id', 'computed_at', name='agent_computed_at')
    )
    op.create_index('ix_reputation_snapshots_agent_id_computed_at', 'reputation_snapshots', ['agent_id', 'computed_at'], unique=False)
    op.create_index('ix_reputation_snapshots_score', 'reputation_snapshots', ['score'], unique=False)
    op.create_table('services',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('slug', app.db.types.LowercaseString(length=96), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=280), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'published', 'unavailable', 'archived', 'suspended', name='service_status'), server_default='draft', nullable=False),
    sa.Column('pricing_model', sa.Enum('fixed', 'per_unit', 'hourly', 'negotiated', name='pricing_model'), server_default='fixed', nullable=False),
    sa.Column('price', sa.Numeric(precision=38, scale=6), nullable=True),
    sa.Column('price_currency', sa.String(length=12), server_default='USDC', nullable=False),
    sa.Column('price_unit', sa.String(length=32), nullable=True),
    sa.Column('min_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('delivery_time_hours', sa.Integer(), nullable=True),
    sa.Column('auto_release_hours', sa.Integer(), server_default='168', nullable=False),
    sa.Column('max_concurrent_orders', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'::varchar[]"), nullable=False),
    sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('completed_order_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('review_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('rating_sum', sa.Integer(), server_default='0', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("pricing_model <> 'per_unit' OR price_unit IS NOT NULL", name=op.f('ck_services_per_unit_requires_unit')),
    sa.CheckConstraint("pricing_model = 'negotiated' OR price IS NOT NULL", name=op.f('ck_services_price_required_unless_negotiated')),
    sa.CheckConstraint("slug ~ '^[a-z0-9][a-z0-9-]{1,95}$'", name=op.f('ck_services_slug_format')),
    sa.CheckConstraint("status <> 'published' OR published_at IS NOT NULL", name=op.f('ck_services_published_requires_timestamp')),
    sa.CheckConstraint('auto_release_hours > 0', name=op.f('ck_services_auto_release_positive')),
    sa.CheckConstraint('completed_order_count >= 0 AND completed_order_count <= order_count', name=op.f('ck_services_completed_within_order_count')),
    sa.CheckConstraint('delivery_time_hours IS NULL OR delivery_time_hours > 0', name=op.f('ck_services_delivery_time_positive')),
    sa.CheckConstraint('max_concurrent_orders IS NULL OR max_concurrent_orders > 0', name=op.f('ck_services_max_concurrent_positive')),
    sa.CheckConstraint('max_quantity IS NULL OR max_quantity >= min_quantity', name=op.f('ck_services_max_quantity_gte_min')),
    sa.CheckConstraint('min_quantity >= 1', name=op.f('ck_services_min_quantity_at_least_one')),
    sa.CheckConstraint('order_count >= 0', name=op.f('ck_services_order_count_non_negative')),
    sa.CheckConstraint('price IS NULL OR price > 0', name=op.f('ck_services_price_positive')),
    sa.CheckConstraint('rating_sum >= 0 AND rating_sum <= review_count * 5', name=op.f('ck_services_rating_sum_within_bounds')),
    sa.CheckConstraint('review_count >= 0 AND review_count <= completed_order_count', name=op.f('ck_services_reviews_cannot_exceed_completed_orders')),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], name=op.f('fk_services_agent_id_agents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_services_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('agent_id', 'slug', name='agent_slug')
    )
    op.create_index('ix_services_agent_id', 'services', ['agent_id'], unique=False)
    op.create_index('ix_services_category_id_status', 'services', ['category_id', 'status'], unique=False)
    op.create_index('ix_services_price', 'services', ['price'], unique=False)
    op.create_index('ix_services_search_vector', 'services', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_services_status_published_at', 'services', ['status', 'published_at'], unique=False)
    op.create_index('ix_services_tags', 'services', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('orders',
    sa.Column('reference', sa.String(length=16), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('provider_agent_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending_payment', 'funded', 'in_progress', 'delivered', 'completed', 'disputed', 'cancelled', 'refunded', 'expired', name='order_status'), server_default='pending_payment', nullable=False),
    sa.Column('quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=38, scale=6), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=38, scale=6), nullable=False),
    sa.Column('platform_fee', sa.Numeric(precision=38, scale=6), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=38, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=12), server_default='USDC', nullable=False),
    sa.Column('platform_fee_bps', sa.Integer(), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('input_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('output_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('funding_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('auto_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'completed') = (completed_at IS NOT NULL)", name=op.f('ck_orders_completed_at_matches_status')),
    sa.CheckConstraint('completed_at IS NULL OR funded_at IS NOT NULL', name=op.f('ck_orders_completion_requires_funding')),
    sa.CheckConstraint('delivered_at IS NULL OR funded_at IS NOT NULL', name=op.f('ck_orders_delivery_requires_funding')),
    sa.CheckConstraint('platform_fee >= 0', name=op.f('ck_orders_platform_fee_non_negative')),
    sa.CheckConstraint('platform_fee_bps >= 0 AND platform_fee_bps <= 10000', name=op.f('ck_orders_platform_fee_bps_in_range')),
    sa.CheckConstraint('quantity >= 1', name=op.f('ck_orders_quantity_at_least_one')),
    sa.CheckConstraint('subtotal = unit_price * quantity', name=op.f('ck_orders_subtotal_matches_line')),
    sa.CheckConstraint('subtotal > 0', name=op.f('ck_orders_subtotal_positive')),
    sa.CheckConstraint('total_amount = subtotal + platform_fee', name=op.f('ck_orders_total_matches_components')),
    sa.CheckConstraint('total_amount > 0', name=op.f('ck_orders_total_amount_positive')),
    sa.CheckConstraint('unit_price > 0', name=op.f('ck_orders_unit_price_positive')),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('fk_orders_buyer_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['provider_agent_id'], ['agents.id'], name=op.f('fk_orders_provider_agent_id_agents'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_orders_service_id_services'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('reference', name=op.f('uq_orders_reference'))
    )
    op.create_index('ix_orders_auto_release_due', 'orders', ['auto_release_at'], unique=False, postgresql_where=sa.text("status = 'delivered'"))
    op.create_index('ix_orders_buyer_id_created_at', 'orders', ['buyer_id', 'created_at'], unique=False)
    op.create_index('ix_orders_funding_deadline', 'orders', ['funding_deadline'], unique=False, postgresql_where=sa.text("status = 'pending_payment'"))
    op.create_index('ix_orders_provider_agent_id_status', 'orders', ['provider_agent_id', 'status'], unique=False)
    op.create_index('ix_orders_service_id', 'orders', ['service_id'], unique=False)
    op.create_index('ix_orders_status_created_at', 'orders', ['status', 'created_at'], unique=False)
    op.create_table('escrows',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('none', 'funding', 'funded', 'releasing', 'released', 'refunding', 'refunded', 'disputed', 'failed', name='escrow_status'), server_default='none', nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', app.db.types.EthereumAddress(length=42), nullable=True),
    sa.Column('onchain_escrow_id', sa.String(length=78), nullable=True),
    sa.Column('token_address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('token_symbol', sa.String(length=12), server_default='USDC', nullable=False),
    sa.Column('token_decimals', sa.Integer(), server_default='6', nullable=False),
    sa.Column('amount', sa.Numeric(precision=38, scale=6), nullable=False),
    sa.Column('released_amount', sa.Numeric(precision=38, scale=6), server_default='0', nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=38, scale=6), server_default='0', nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=38, scale=6), server_default='0', nullable=False),
    sa.Column('buyer_address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('provider_address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('funded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disputed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_reason', sa.Text(), nullable=True),
    sa.Column('dispute_resolution', sa.Enum('released_to_provider', 'refunded_to_buyer', 'split', name='dispute_resolution'), nullable=True),
    sa.Column('dispute_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispute_resolved_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'released') = (released_at IS NOT NULL)", name=op.f('ck_escrows_released_at_matches_status')),
    sa.CheckConstraint("status NOT IN ('funded','releasing','released','refunding','refunded','disputed') OR funded_at IS NOT NULL", name=op.f('ck_escrows_funded_states_require_funded_at')),
    sa.CheckConstraint('(dispute_resolution IS NULL) = (dispute_resolved_at IS NULL)', name=op.f('ck_escrows_dispute_resolution_consistent')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_escrows_amount_positive')),
    sa.CheckConstraint('chain_id > 0', name=op.f('ck_escrows_chain_id_positive')),
    sa.CheckConstraint('dispute_resolved_at IS NULL OR disputed_at IS NOT NULL', name=op.f('ck_escrows_resolution_requires_dispute')),
    sa.CheckConstraint('fee_amount <= amount', name=op.f('ck_escrows_fee_within_deposit')),
    sa.CheckConstraint('fee_amount >= 0', name=op.f('ck_escrows_fee_non_negative')),
    sa.CheckConstraint('refunded_amount >= 0', name=op.f('ck_escrows_refunded_non_negative')),
    sa.CheckConstraint('released_amount + refunded_amount <= amount', name=op.f('ck_escrows_payouts_cannot_exceed_deposit')),
    sa.CheckConstraint('released_amount >= 0', name=op.f('ck_escrows_released_non_negative')),
    sa.CheckConstraint('token_decimals BETWEEN 0 AND 36', name=op.f('ck_escrows_token_decimals_sane')),
    sa.ForeignKeyConstraint(['dispute_resolved_by'], ['users.id'], name=op.f('fk_escrows_dispute_resolved_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_escrows_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_escrows')),
    sa.UniqueConstraint('contract_address', 'onchain_escrow_id', name='contract_onchain_id'),
    sa.UniqueConstraint('order_id', name=op.f('uq_escrows_order_id'))
    )
    op.create_index('ix_escrows_buyer_address', 'escrows', ['buyer_address'], unique=False)
    op.create_index('ix_escrows_provider_address', 'escrows', ['provider_address'], unique=False)
    op.create_index('ix_escrows_status', 'escrows', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('order', 'payment', 'message', 'reputation', 'security', 'system', name='notification_category'), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('locale', sa.String(length=10), server_default='en', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_order_id', sa.UUID(), nullable=True),
    sa.Column('related_agent_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_agent_id'], ['agents.id'], name=op.f('fk_notifications_related_agent_id_agents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_order_id'], ['orders.id'], name=op.f('fk_notifications_related_order_id_orders'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_related_order_id', 'notifications', ['related_order_id'], unique=False)
    op.create_index('ix_notifications_user_id_created_at', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL AND archived_at IS NULL'))
    op.create_table('order_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('from_status', sa.String(length=32), nullable=True),
    sa.Column('to_status', sa.String(length=32), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_order_events_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events'))
    )
    op.create_index('ix_order_events_order_id_created_at', 'order_events', ['order_id', 'created_at'], unique=False)
    op.create_table('reviews',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('subject_agent_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('published', 'withdrawn', 'removed', name='review_status'), server_default='published', nullable=False),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removal_reason', sa.String(length=256), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'removed') = (removed_at IS NOT NULL)", name=op.f('ck_reviews_removed_at_matches_status')),
    sa.CheckConstraint("(status = 'withdrawn') = (withdrawn_at IS NOT NULL)", name=op.f('ck_reviews_withdrawn_at_matches_status')),
    sa.CheckConstraint('(response_body IS NULL) = (response_at IS NULL)', name=op.f('ck_reviews_response_consistent')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_rating_in_range')),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_reviews_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_reviews_order_id_orders'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_reviews_service_id_services'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_agent_id'], ['agents.id'], name=op.f('fk_reviews_subject_agent_id_agents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('order_id', name=op.f('uq_reviews_order_id'))
    )
    op.create_index('ix_reviews_author_id', 'reviews', ['author_id'], unique=False)
    op.create_index('ix_reviews_created_at', 'reviews', ['created_at'], unique=False)
    op.create_index('ix_reviews_service_id_status', 'reviews', ['service_id', 'status'], unique=False)
    op.create_index('ix_reviews_subject_agent_id_status', 'reviews', ['subject_agent_id', 'status'], unique=False)
    op.create_table('chain_transactions',
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('escrow_id', sa.UUID(), nullable=True),
    sa.Column('tx_hash', app.db.types.TransactionHash(length=66), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('tx_type', sa.Enum('escrow_fund', 'escrow_release', 'escrow_refund', 'platform_fee', 'token_approval', name='transaction_type'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'reverted', 'dropped', 'reorged', name='transaction_status'), server_default='pending', nullable=False),
    sa.Column('from_address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('to_address', app.db.types.EthereumAddress(length=42), nullable=True),
    sa.Column('amount', sa.Numeric(precision=38, scale=6), nullable=True),
    sa.Column('token_address', app.db.types.EthereumAddress(length=42), nullable=True),
    sa.Column('block_number', sa.BigInteger(), nullable=True),
    sa.Column('block_hash', sa.String(length=66), nullable=True),
    sa.Column('log_index', sa.Integer(), nullable=True),
    sa.Column('confirmations', sa.Integer(), server_default='0', nullable=False),
    sa.Column('gas_used', sa.BigInteger(), nullable=True),
    sa.Column('effective_gas_price', sa.BigInteger(), nullable=True),
    sa.Column('broadcast_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=512), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'confirmed') = (confirmed_at IS NOT NULL)", name=op.f('ck_chain_transactions_confirmed_at_matches_status')),
    sa.CheckConstraint("status NOT IN ('confirmed','reverted') OR block_number IS NOT NULL", name=op.f('ck_chain_transactions_mined_requires_block_number')),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_chain_transactions_amount_non_negative')),
    sa.CheckConstraint('block_number IS NULL OR block_number >= 0', name=op.f('ck_chain_transactions_block_number_valid')),
    sa.CheckConstraint('confirmations >= 0', name=op.f('ck_chain_transactions_confirmations_non_negative')),
    sa.ForeignKeyConstraint(['escrow_id'], ['escrows.id'], name=op.f('fk_chain_transactions_escrow_id_escrows'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_chain_transactions_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chain_transactions')),
    sa.UniqueConstraint('chain_id', 'tx_hash', name='chain_tx_hash')
    )
    op.create_index('ix_chain_transactions_block_number', 'chain_transactions', ['block_number'], unique=False)
    op.create_index('ix_chain_transactions_escrow_id', 'chain_transactions', ['escrow_id'], unique=False)
    op.create_index('ix_chain_transactions_order_id', 'chain_transactions', ['order_id'], unique=False)
    op.create_index('ix_chain_transactions_pending', 'chain_transactions', ['chain_id', 'broadcast_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    op.create_index('ix_chain_transactions_status', 'chain_transactions', ['status'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', name='notification_channel'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sent', 'delivered', 'failed', 'suppressed', name='notification_delivery_status'), server_default='pending', nullable=False),
    sa.Column('destination', sa.String(length=320), nullable=True),
    sa.Column('provider_message_id', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'failed') = (failed_at IS NOT NULL)", name=op.f('ck_notification_deliveries_failed_at_matches_status')),
    sa.CheckConstraint("channel <> 'email' OR destination IS NOT NULL", name=op.f('ck_notification_deliveries_email_requires_destination')),
    sa.CheckConstraint("status NOT IN ('sent', 'delivered') OR sent_at IS NOT NULL", name=op.f('ck_notification_deliveries_sent_states_require_sent_at')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_notification_deliveries_attempt_count_non_negative')),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('notification_id', 'channel', name='notification_channel')
    )
    op.create_index('ix_notification_deliveries_notification_id', 'notification_deliveries', ['notification_id'], unique=False)
    op.create_index('ix_notification_deliveries_provider_message_id', 'notification_deliveries', ['provider_message_id'], unique=False)
    op.create_index('ix_notification_deliveries_retry_due', 'notification_deliveries', ['next_retry_at'], unique=False, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###

    # Maintain services.search_vector in the database so every write path --
    # API, migration, or manual correction -- keeps full-text search correct.
    op.execute(CREATE_SEARCH_VECTOR_FUNCTION)
    op.execute(CREATE_SEARCH_VECTOR_TRIGGER)


def downgrade() -> None:
    op.execute(DROP_SEARCH_VECTOR_TRIGGER)
    op.execute(DROP_SEARCH_VECTOR_FUNCTION)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notification_deliveries_retry_due', table_name='notification_deliveries', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_notification_deliveries_provider_message_id', table_name='notification_deliveries')
    op.drop_index('ix_notification_deliveries_notification_id', table_name='notification_deliveries')
    op.drop_table('notification_deliveries')
    op.drop_index('ix_chain_transactions_status', table_name='chain_transactions')
    op.drop_index('ix_chain_transactions_pending', table_name='chain_transactions', postgresql_where=sa.text("status = 'pending'"))
    op.drop_index('ix_chain_transactions_order_id', table_name='chain_transactions')
    op.drop_index('ix_chain_transactions_escrow_id', table_name='chain_transactions')
    op.drop_index('ix_chain_transactions_block_number', table_name='chain_transactions')
    op.drop_table('chain_transactions')
    op.drop_index('ix_reviews_subject_agent_id_status', table_name='reviews')
    op.drop_index('ix_reviews_service_id_status', table_name='reviews')
    op.drop_index('ix_reviews_created_at', table_name='reviews')
    op.drop_index('ix_reviews_author_id', table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('ix_order_events_order_id_created_at', table_name='order_events')
    op.drop_table('order_events')
    op.drop_index('ix_notifications_user_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL AND archived_at IS NULL'))
    op.drop_index('ix_notifications_user_id_created_at', table_name='notifications')
    op.drop_index('ix_notifications_related_order_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_escrows_status', table_name='escrows')
    op.drop_index('ix_escrows_provider_address', table_name='escrows')
    op.drop_index('ix_escrows_buyer_address', table_name='escrows')
    op.drop_table('escrows')
    op.drop_index('ix_orders_status_created_at', table_name='orders')
    op.drop_index('ix_orders_service_id', table_name='orders')
    op.drop_index('ix_orders_provider_agent_id_status', table_name='orders')
    op.drop_index('ix_orders_funding_deadline', table_name='orders', postgresql_where=sa.text("status = 'pending_payment'"))
    op.drop_index('ix_orders_buyer_id_created_at', table_name='orders')
    op.drop_index('ix_orders_auto_release_due', table_name='orders', postgresql_where=sa.text("status = 'delivered'"))
    op.drop_table('orders')
    op.drop_index('ix_services_tags', table_name='services', postgresql_using='gin')
    op.drop_index('ix_services_status_published_at', table_name='services')
    op.drop_index('ix_services_search_vector', table_name='services', postgresql_using='gin')
    op.drop_index('ix_services_price', table_name='services')
    op.drop_index('ix_services_category_id_status', table_name='services')
    op.drop_index('ix_services_agent_id', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_reputation_snapshots_score', table_name='reputation_snapshots')
    op.drop_index('ix_reputation_snapshots_agent_id_computed_at', table_name='reputation_snapshots')
    op.drop_table('reputation_snapshots')
    op.drop_index('ix_agent_domain_challenges_agent_id', table_name='agent_domain_challenges')
    op.drop_table('agent_domain_challenges')
    op.drop_index('ix_agents_status_published_at', table_name='agents')
    op.drop_index('ix_agents_owner_id', table_name='agents')
    op.drop_index('ix_agents_capabilities', table_name='agents', postgresql_using='gin')
    op.drop_table('agents')
    op.drop_index('uq_wallets_one_payout_per_user', table_name='wallets', postgresql_where=sa.text('is_payout'))
    op.drop_index('ix_wallets_user_id', table_name='wallets')
    op.drop_table('wallets')
    op.drop_index('ix_sessions_user_id_expires_at', table_name='sessions')
    op.drop_index('ix_sessions_expires_at', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_notification_preferences_user_id', table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index('ix_users_status_created_at', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_siwe_nonces_expires_at', table_name='siwe_nonces')
    op.drop_table('siwe_nonces')
    op.drop_index('ix_categories_parent_id_sort_order', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###

    for enum_name in ENUM_TYPES:
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
