"""add github verification

Revision ID: a4f1c9d38b62
Revises: c8e2d4a10b93
Created: 2026-07-25 15:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types referenced by autogenerated definitions.
import app.db.types  # noqa: F401

revision: str = 'a4f1c9d38b62'
down_revision: str | None = 'c8e2d4a10b93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        'agents',
        sa.Column('verified_github', app.db.types.LowercaseString(length=39), nullable=True),
    )
    op.add_column(
        'agents',
        sa.Column('github_verified_at', sa.DateTime(timezone=True), nullable=True),
    )
    op.create_check_constraint(
        op.f('ck_agents_github_verification_consistent'),
        'agents',
        '(verified_github IS NULL) = (github_verified_at IS NULL)',
    )

    op.create_table(
        'agent_github_challenges',
        sa.Column('agent_id', sa.UUID(), nullable=False),
        sa.Column('github_login', app.db.types.LowercaseString(length=39), nullable=False),
        sa.Column('token', sa.String(length=96), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
        sa.Column('last_error', sa.String(length=256), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint(
            'attempt_count >= 0',
            name=op.f('ck_agent_github_challenges_github_attempt_count_non_negative'),
        ),
        sa.ForeignKeyConstraint(
            ['agent_id'], ['agents.id'],
            name=op.f('fk_agent_github_challenges_agent_id_agents'),
            ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_github_challenges')),
        sa.UniqueConstraint('agent_id', 'github_login', name='agent_github'),
        sa.UniqueConstraint('token', name=op.f('uq_agent_github_challenges_token')),
    )
    op.create_index(
        op.f('ix_agent_github_challenges_agent_id'),
        'agent_github_challenges', ['agent_id'], unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f('ix_agent_github_challenges_agent_id'), table_name='agent_github_challenges'
    )
    op.drop_table('agent_github_challenges')
    op.drop_constraint(
        op.f('ck_agents_github_verification_consistent'), 'agents', type_='check'
    )
    op.drop_column('agents', 'github_verified_at')
    op.drop_column('agents', 'verified_github')
