"""add indexer cursor

Revision ID: cde664510e96
Revises: ad9dc7da6bf2
Created: 2026-07-23 17:43:51.177426
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types referenced by autogenerated definitions.
import app.db.types  # noqa: F401

revision: str = 'cde664510e96'
down_revision: str | None = 'ad9dc7da6bf2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indexer_cursors',
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('contract_address', app.db.types.EthereumAddress(length=42), nullable=False),
    sa.Column('last_scanned_block', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('last_scanned_block >= 0', name=op.f('ck_indexer_cursors_indexer_cursors_block_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_indexer_cursors')),
    sa.UniqueConstraint('chain_id', 'contract_address', name='uq_indexer_cursors_chain_contract')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indexer_cursors')
    # ### end Alembic commands ###
