"""add subscriptions

Revision ID: b7d1e0f92a34
Revises: a4f1c9d38b62
Created: 2026-07-26 09:00:00.000000
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Custom column types referenced by autogenerated definitions.
import app.db.types  # noqa: F401

revision: str = 'b7d1e0f92a34'
down_revision: str | None = 'a4f1c9d38b62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        'subscription_plans',
        sa.Column('plan_id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(length=80), nullable=False),
        sa.Column('description', sa.String(length=400), nullable=True),
        sa.Column('tier', sa.String(length=40), nullable=False),
        sa.Column(
            'interval',
            sa.Enum('monthly', 'yearly', name='subscription_interval'),
            nullable=False,
        ),
        sa.Column('token_address', app.db.types.EthereumAddress(length=42), nullable=False),
        sa.Column('token_symbol', sa.String(length=12), server_default='USDC', nullable=False),
        sa.Column('token_decimals', sa.Integer(), server_default='6', nullable=False),
        sa.Column('price', sa.Numeric(precision=38, scale=6), nullable=False),
        sa.Column('period_seconds', sa.BigInteger(), nullable=False),
        sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
        sa.UniqueConstraint('plan_id', name=op.f('uq_subscription_plans_plan_id')),
    )

    op.create_table(
        'subscriptions',
        sa.Column('subscriber_address', app.db.types.EthereumAddress(length=42), nullable=False),
        sa.Column('plan_id', sa.BigInteger(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
        sa.Column('auto_renew_cancelled', sa.Boolean(), server_default='false', nullable=False),
        sa.Column('last_payment_tx', app.db.types.TransactionHash(length=66), nullable=True),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'],
            name=op.f('fk_subscriptions_user_id_users'), ondelete='SET NULL',
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
        sa.UniqueConstraint('subscriber_address', 'plan_id', name='subscriber_plan'),
    )
    op.create_index(
        op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False
    )
    op.create_index(
        op.f('ix_subscriptions_current_period_end'),
        'subscriptions', ['current_period_end'], unique=False,
    )

    op.create_table(
        'subscription_payments',
        sa.Column('tx_hash', app.db.types.TransactionHash(length=66), nullable=False),
        sa.Column('log_index', sa.Integer(), nullable=False),
        sa.Column('subscriber_address', app.db.types.EthereumAddress(length=42), nullable=False),
        sa.Column('plan_id', sa.BigInteger(), nullable=False),
        sa.Column('amount', sa.Numeric(precision=38, scale=6), nullable=False),
        sa.Column('token_symbol', sa.String(length=12), server_default='USDC', nullable=False),
        sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
        sa.Column('block_number', sa.BigInteger(), nullable=False),
        sa.Column('block_hash', sa.String(length=66), nullable=False),
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_payments')),
        sa.UniqueConstraint('tx_hash', 'log_index', name='uq_subscription_payment_log'),
    )
    op.create_index(
        op.f('ix_subscription_payments_subscriber'),
        'subscription_payments', ['subscriber_address'], unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        op.f('ix_subscription_payments_subscriber'), table_name='subscription_payments'
    )
    op.drop_table('subscription_payments')
    op.drop_index(
        op.f('ix_subscriptions_current_period_end'), table_name='subscriptions'
    )
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('subscription_plans')
    op.execute('DROP TYPE IF EXISTS subscription_interval')
